# Use an official Node.js image as a base image
FROM node:14 as builder

# Set the working directory to /app
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the entire project to the working directory
COPY . .

# Build the Angular app in production mode
RUN npm run build --prod

# Use an official Nginx image as a base image
FROM nginx:1.21.1

# Copy the built Angular app from the builder stage
COPY --from=builder /app/dist /usr/share/nginx/html

# Expose the default HTTP port
EXPOSE 80

# Nginx configuration (you may need to customize this)
COPY nginx.conf /etc/nginx/conf.d/default.conf
